    sudo: false
    language: c
     
    addons:
      apt:
        packages:
        - pandoc
     
    script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh -t Carbonite | bash
     
    branches:
      only:
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
