    sudo: false
    language: c
     
    addons:
      apt:
        packages:
        - pandoc
     
    script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | sed 's/### Create the final zipfile for the addon./rm \$releasedir\/CarboniteClassic\/CarboniteClassic\.toc/g' | bash
     
    branches:
      only:
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
